- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.EventStore/Checkpoint.fs
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/EventStoreSource.fs
- src/Propulsion.EventStore/Infrastructure.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStore/StripedIngester.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
This derives from a set of work carried out in [this long-running `dotnet-templates` PR](https://github.com/jet/dotnet-templates/pull/16), which spawned a lot of code that resides in this repo today.
> Add EventStoreSource

- CHANGELOG.md
- src/Propulsion.Kafka/Codec.fs
This PR moves the `RenderedSpan` codec into a nested namespace `Propulsion.Codec.NewtonsoftJson` for the following reasons:
- While it's use is closely correlated with use of `Propulsion.Kafka`, there's nothing actually coupling
- Serializers are a Reason For Change, so being able to calve this off as a new nuget (or series thereof) without source changes is a good thing
- this same naming scheme [is used in `Equinox.Codec`](https://github.com/jet/equinox/blob/master/src/Equinox.Codec/Codec.fs)
> Renamespace Codec

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
This only triggers minor changes, but this RC phases of Equinox and Propulsion are likely to result in effectively concurrent releases (I'm effectively integration testing them in https://github.com/jet/dotnet-templates atm)
> Target Equinox 2.0.0-rc1

- CHANGELOG.md
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/StripedIngester.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
Fixes race conditions in how the ES ingestion logic transitions from reading in parallel to tailing, see #10
Also removes idling bug which dramatically reduces CPU consumption (and should also improve throughput)
> Fix EventStore Gorge -> Tail transition #10

- .gitignore
- src/Propulsion.Kafka0/ConfluentKafka1Shims.fs
- src/Propulsion.Kafka0/JetConfluentKafkaFSharpShims.fs
move kafka config shims under a namespace Propulsion.Kafka0.* so doesnt overlap with original
Some projects may want to use both `Propulsion.Kafka0` and `Jet.ConfluentKafka.FSharp v0` in the same project.
If some types have the the same fullname (namespace + name), is not possibile in F# to discriminate
the two, doesnt matter if are defined in different assemblies
> Make kafka0 config to another namespace

- CHANGELOG.md
- src/Propulsion.EventStore/StripedIngester.fs
Resolves #16 by not counting read-ahead batches against the maximum number of batches to read ahead when reading from EventStore in striped/'gorge' mode
> Improve striped mode in-flight batch reservation algorithm

- CHANGELOG.md
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.EventStore/Checkpoint.fs
- src/Propulsion.EventStore/EventStoreSource.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.Kafka0/Propulsion.Kafka0.fsproj
- src/Propulsion/Propulsion.fsproj
The above releases need to be in lockstep so pushing this release in order to simplify future updates despite there not being any significant gain or relevance for Propulsion (which can work equally with FsCodec 1.0.0-rc1 and 1.0.0-rc2)
> Target Equinox 2.0.0-rc6, FsCodec 1.0.0-rc2

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.Cosmos/EquinoxCosmosParser.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/EventStoreSource.fs
- src/Propulsion.Kafka/Codec.fs
- src/Propulsion/Streams.fs
- tests/Propulsion.Tests/StreamStateTests.fs
- tools/Propulsion.Tool/Program.fs
This cleanup, prompted by shimming otherwise required in https://github.com/jet/dotnet-templates replaces usages of `IEvent` alongside an `index` by replacing with `IIndexedEvent`. This also allows us to simplify the naming of RenderedSpan vs RenderedSummary (`IsUnfold` can be used to distinguish as necessary)
> Standardize on IIndexedevent for event representations

- CHANGELOG.md
- src/Propulsion.EventStore/Checkpoint.fs
This cleanup removes [a shim from the templates](https://github.com/jet/dotnet-templates/blob/ead62bb379bca2a69a74613bb19b31e990f3e6b4/propulsion-sync/Program.fs#L553)
> Fix transmute signature

- CHANGELOG.md
- src/Propulsion.EventStore/Checkpoint.fs
The current algorithm _almost_ reduces the checkpoint writing frequency, but not quite.
This completes the job...
> Correct redundant checkpoint writing

- CHANGELOG.md
- src/Propulsion.Kafka/Consumers.fs
Bug (and fix) identified by @nosman with regard to `null` keys not being handled
> StreamKeyEventSequencer: Handle null keys

- CHANGELOG.md
- src/Propulsion.EventStore/Checkpoint.fs
My [last attempt](https://github.com/jet/propulsion/pull/42) works correctly, in that it generates correct values.
However, a key oversight is that `transmute` is passed the _post_ state, so will incorporate the event we are writing.
This more directly represents the situation, by having the `decide` function emit either a `Checkpointed` or an `Updated` indicating the intent.
This simplifies the `transmute` function significantly.
> Actually write checkpoints when using Equinox.Cosmos

- CHANGELOG.md
- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- src/Propulsion.Cosmos/CosmosSource.fs
- src/Propulsion.Cosmos/Infrastructure.fs
- tools/Propulsion.Tool/Program.fs
This PR reorganizes the CFP signatures to align with the Connector changes in https://github.com/jet/equinox/pull/171
The CreateClient in this PR is a hack and doesn't log correctly, hence this probably won't mrege/release until the next Equinox release
> Cosmos: Change Arguments to use DocumentClient

- Directory.Build.props
`Microsoft.NETFramework.ReferenceAssemblies` was still on `1.0.0-preview.2` while `1.0.0` has been released. Updating these.
> update reference assemblies to 1.0.0

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.Cosmos/EquinoxCosmosParser.fs
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.EventStore/Checkpoint.fs
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/EventStoreSource.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.Kafka/Codec.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.Kafka0/Propulsion.Kafka0.fsproj
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/Streams.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
- tests/Propulsion.Tests/ProgressTests.fs
This feeds through changes logically implied by Equinox adopting `FsCodec.StreamName`; all Stream Names are now managed in canonical `{category}-{aggregateId}` form
The key benefit of this for the programming model is that the `dotnet-templates` no longer need to furnish a `categorize` function, which allows [`StreamName`'s associated documentation](https://github.com/jet/FsCodec/tree/master#stream-naming-conventions) to describe then routing and matching of all streams being processed.
- Target [Equinox 2.0.0-rc9](https://github.com/jet/equinox/releases/tag/2.0.0-rc9)
- Target [FsCodec 2.0.0-rc3](https://github.com/jet/FsCodec/pull/31)
> Use FsCodec.StreamName

- CHANGELOG.md
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
- `StreamsSync`: Add `* 'outcome` to `handle` function signature
- `StreamsProducerSink`: Added overload to facilitate `prepare` make production of an output `option`al and admitting processing of Stats
@fnipo @kimserey
> Add outcome to prepare, make producing optional

- CHANGELOG.md
- src/Propulsion.EventStore/Checkpoint.fs
Applying conventions in https://github.com/jet/dotnet-templates/pull/54 to `module Propulsion.EventStore.Checkpoint`
> Apply module Aggregate conventions to Checkpoint

- CHANGELOG.md
- src/Propulsion.Kafka/Consumers.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
This extends the main Kafka Consumption overloads (which focus on overloads presenting `Confluent.Kafka`s `Message.Key` and `Message.Value` as the key ingredients for mapping to a `StreamEvent`)
Breaking changes:
- `Propulsion.Kafka.StreamsConsumer`'s `Start` methods move to `Propulsion.Core.StreamsConsumer` (i.e. prefixing `StreamsConsumer` with `Core.` should work)
- `Propulsion.Kafka.Core.StreamKeyEventSequencer` becomes `Propulsion.Kafka.StreamNameSequenceGenerator`
- `Propulsion.Kafka.Core.StreamKeyEventSequencer.ToStreamEvent` becomes `Propulsion.Kafka.KeyValueToStreamEvent`
- `Propulsion.Kafka.StreamsConsumer` now exposes a single (new) signature with a parameter: `consumeResultToStreamEvents : ConsumeResult<_, _> -> Propulsion.Streams.StreamEvent<_> seq`, which can be implemented …
> Extend Kafka StreamsConsumer's facilities re mapping to `StreamEvent`

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
resolves #58:
- Simplifies many messy type signatures, particularly wrt egregious inclusion of the Write Position alongside the `'Outcome` presented to Stats handlers (this removes a lot of inconsistency in consumer code when one adjusts the overall Projector Configuration)
- replaces direct usage of an `int64` Write Position in the Handler signature with an explicit `SpanResult`:
> ```fsharp
> /// Represents progress attained during the processing of the supplied <c>StreamSpan</c> for a given <c>StreamName</c>.
> /// This will be reflected in adjustments to the Write Position for the stream.
> /// Incoming <c>StreamEvents</c> with <c>Index</c>es prior to the active Write Position are proactively dropped from incoming buffers.
> type SpanResult =
>    /// Indicates all events supplied in …
```
> Clean up Stats types, add SpanResult

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
- tests/Propulsion.Tests/StreamStateTests.fs
In lieu of doing lots of logging in https://github.com/jet/dotnet-templates/pull/65, this adds an `abstract HandleExn` method to the `Stats` type, and removes defaulting in order to force the consideration of how to manifest contextual information about error rates out to the caller/host
> Surface exceptions to incite logging

- CHANGELOG.md
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
- tools/Propulsion.Tool/Program.fs
`Scheduling.Stats` needs to be `abstract` in order to trigger usage of an alternative that provides an `abstract HandleExn`
> Make Scheduling.Stats abstract; stats consistency

- CHANGELOG.md
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
`StreamsSync` was still reliant on a raw `int64` post-position result; for consistency (highlighted by dotnet-templates), this converges it on the same signature
> Upgrade StreamsResult to SpanResult

- CHANGELOG.md
- src/Propulsion/Streams.fs
Fixes an issue reported and repro'd internally by @fnipo where test scenarios hang when run repeatedly.
This had gone unnoticed (despite automated tests and more than a year of heavy production usage) as typically one only runs (and from a performance perspective, should only run) a single StreamsProjector per Process.
> Fix StreamsProjector hang when >1 instance

- CHANGELOG.md
- src/Propulsion.Kafka/Producers.fs
To align with Confluent.Kafka 1.5.0 and typical usage patterns, this applies a default producer timeout of 5ms (it previously was 0ms, so this is do a degree a breaking change)
> Kafka: Make default Producer linger 5ms

- CHANGELOG.md
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.Kafka0/Propulsion.Kafka0.fsproj
Applies technique used in FsKafka 1.5.1 (can work against `FsKafka >= 1.5`, but pinning to `< 1.6` so we can remove obsolete overloads in timely fashion)
> Correct Kafka Polling pause

- CHANGELOG.md
- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.Cosmos/CosmosSource.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion/Streams.fs
Adjustments to logging for consistency purposes (made in the course of implementing pruning)
Includes `HandleExn` signature change (it was originally incorrect)
> Logging consistency tweaks

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Streams.fs
Cleaning up inconsistencies as discussed with @gardito
> Consistently expose idleDelay/pumpInterval arguments

- CHANGELOG.md
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
Via @gardito, removes a custom `idleDelay` used for `StreamsProducerSink` as this leads to excessive CPU consumption
> Fix StreamsProducerSink idle

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion/Streams.fs
While the CosmosDB document size limit is ~2MB, the limit `CosmosSink` imposes is 1MB/16384 events based on that being the limit of the size of arguments that may be submitted on a stored procedure invocation.
Performance tuning on the archiver template has made it clear that:
- self-limiting to 80KB yields a predictable RU cost of < 100
- self-limiting to 1MB can cause continual rejection of requests when 400RU is allocated (charges run up to ~1600RU can be sustained)
- self-limiting to 512K has not caused such a hang (charges stay < 500RU)
- self-limiting to 128K seems to trigger significant jitter in the charges
As a result, this PR exposes the `maxEvents` and `maxBytes` parameters in order that the default in the templates can be shifted downward into the 512K (or lower) thresholds in …
> Cosmos: Expose maxBytes, maxEvents params on CosmosSink

- CHANGELOG.md
- src/Propulsion.Kafka/Producers.fs
Propulsion.Kafka defaults the `acks` for the `Producer` wrapper to `Acks.Leader`.
That was carelessness a long time ago; this breaking change requires client code to make a decision as to the policy to use.
> Kafka: Make acks mandatory

- CHANGELOG.md
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
Allow Tool to be used for e.g. environments with only net5.0 runtimes present
> Add RollForward Major for tool

- CHANGELOG.md
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/PropulsionPrometheus.fs
- src/Propulsion/Streams.fs
Applies the same high level approach used to emit metrics from `Propulsion.Cosmos` to `Propulsion.Streams`
Initial impl hosts `Propulsion.Prometheus` within the `Propulsion` package; this will likely be separated out at a future juncture before a full release
> Add Streams scheduler metrics + Prometheus integration

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion/Streams.fs
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
- tests/Propulsion.Tests/StreamStateTests.fs
There's an unbounded Dictionary that maintains, for each stream that's ever been processed:
a) the backlog of events that have yet to be processed. Definitely necessary state.
b) the write position. Provides performance benefits as it enables:
i) deduplication of repeated events coming from the input source (the Ingester can throw away the events before they even get to the scheduler)
ii) proactive discarding because a projection has an awareness of the index of the first event in the stream that's going to be useful. For example, for replication to a warm standby that's already got data, but also when catching up or replaying events for arbitrary projection scenarios. (The underlying mechanism is the same as used for the previous scenario - the handler can yield a response that indicates …
> Streams: Reduce memory usage for streams with only write positions

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
Follow-up to #93 that periodically purges memory consumed by write positions for streams that don't presently have items queued for them.
This can be particularly valuable in constrained memory scenarios, i.e. containers etc.
However, there can be significant negatives to inhibiting the deduplication facility in any way:
- reduced throughput as a result of additional handler calls
- greater load placed on downstream/partner systems, i.e. more roundtrips to databases only to discover the work is redundant
- (where the handler is a producer that has no way of knowing the write position and/or determining whether an event is a repeat that made it through deduplication) redundant messages being produced, with impacts on downstream systems, storage cost or throughput
For these reasons, pruning …
> Streams: Add Purge interval for Write Positions

- CHANGELOG.md
- README.md
- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- src/Propulsion.Cosmos/CosmosSource.fs
- src/Propulsion.Cosmos/EquinoxCosmosParser.fs
- src/Propulsion.Cosmos/Infrastructure.fs
- src/Propulsion.Cosmos/PropulsionCosmosPrometheus.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
In order to avoid mixing V2 and V3 CosmosStores, adding a `CosmosStoreSource` placeholder (implemented using V2 CFP for now)
> Add CosmosStoreSource

- CHANGELOG.md
- README.md
- src/Propulsion.Cosmos/EquinoxCosmosParser.fs
- src/Propulsion.CosmosStore/EquinoxCosmosShims.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
Allows porting from code using Equinox.Cosmos to use Equinox.CosmosStore + Propulsion.CosmosStore.
At present, due to `CosmosStoreSource` being based on the V2 CFP, we need appropriate connection logic, but can't trigger a clash between V2 and V3 variants of Equinox
> CosmosStore: Add Equinox.Cosmos shims

- CHANGELOG.md
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Streams.fs
Tuning for workloads where processing time for some items deviates from the norm significantly.
In order to optimize throughput in such cases, this allows 80% of read batches to be passed to the scheduler in order that it can continue to provide work when a long-running operation from the head of a partition is inhibiting the marking of progress.
The Kafka consumption mechanisms continue to default to a straightforward effective max read ahead of 5 as there is less benefit (and a significant memory consumption cost due to double buffering of inputs).
> Optimize submission for streams scheduler

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.EventStore/EventStoreSource.fs
- src/Propulsion/Streams.fs
This is a breaking change, but a necessary one, as it's existing namespace is highly unintuitive
> Renamespace Streams.Projector.Stats

- CHANGELOG.md
- src/Propulsion.Kafka/Consumers.fs
Replaced by `Propulsion.Streams.Stats` in order to remove unnecessary variance in metrics
> Kafka: Remove StreamsConsumerStats

- CHANGELOG.md
- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- src/Propulsion.Cosmos/CosmosSource.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Streams.fs
- tools/Propulsion.Tool/Program.fs
Ingester and Reader output was previously linked by having `partitionKeyRangeId` in the Serilog `ForContext` Properties. However this proves problematic unless one adds a token for that into the general message template.
This PR replaces messages that lean on the `partitionKeyRangeId` and/or messages from the Ingester using the term `"Uncommitted"` with consistent messages prefixes by `"Reader {partitionId}`
Consumers should remove specific reference to `partitionKeyRangeId`
> Consistently use Reader/partitionId in CFP/Ingester

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSource.fs
- src/Propulsion.Cosmos/EquinoxCosmosParser.fs
- src/Propulsion.Cosmos/Infrastructure.fs
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.Cosmos/PropulsionCosmosPrometheus.fs
- src/Propulsion.Cosmos/ReaderCheckpoint.fs
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
No breaking changes compared to 2.10.0; intended to reduce/simplify diffs in https://github.com/jet/propulsion/pull/113
> CosmosStore: Prepare for V3 port

- CHANGELOG.md
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Projector.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
Equivalent of https://github.com/jet/FsKafka/pull/83 - enables one to cleanly share fate of a set of pipelines hosted in a single process
> Add AwaitWithStopOnCancellation

- CHANGELOG.md
- src/Propulsion/Streams.fs
When using a high max read ahead value for test scenarios, the existing algorithm overflows, leading to no items entering the projector
This tweaks the computation to fix the problem
> StreamsProjector: Fix handling of maxReadAhead Int32.MaxValue

- CHANGELOG.md
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Feed/PeriodicSource.fs
Extend `PeriodicSource` to align with `Propulsion.Feed.FeedSource`, with each `TrancheId` yielded from `readTranches` spawning an individual instance of the `crawl` function (which receives a `TrancheId` to enable distinguishing the source)
> Feed.PeriodicSource: Support multiple Tranches

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosSource.fs
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/Infrastructure.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion/Projector.fs
- tools/Propulsion.Tool/Program.fs
Replaces `CosmosStoreSource.Run`, which inherited semantics from `CosmosSource.Run` with `CosmosStoreSource.Start`, which offers a clear and more composable contract.
This allows one to compose a set of sources and sinks [just as one can do with `FsKafka`](https://github.com/jet/FsKafka/blob/master/README.md#running-and-awaiting-a-pair-of-consumers-until-either-throws).
Note that implementation of semantics regarding clean shutdown via Ctrl-C/Break will now involve explicit use of helpers such as `Async.AwaitKeyboardInterruptAsTaskCancelledException` (currently public in `Propulsion.CosmosStore.Infrastructure`; that does not make sense as a long term home for it)
> CosmosStoreSource: Simplify lifetime management

- CHANGELOG.md
- src/Propulsion.Kafka/Producers.fs
We need Propulsion to publish to secure Kafka clusters. For this, a `IDictionary<string, string> option` needs to be passed to FsKafka's Producer config. If connecting to secure host, this would contain paths of certificate files in the local file system needed for SSL encryption. Hence, adding an optional parameter here in the Producer type's constructor in Propulsion to support this.
> Add config parameter support for FsKafka producer config

- CHANGELOG.md
- README.md
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
As `Equinox.CosmosStore` v `3.0.6` includes a [bugfix that's critical when using `CosmosStorePruner`](https://github.com/jet/equinox/pull/306), we up the dependency herein
> Target Equinox 3.0.6

- CHANGELOG.md
- README.md
- tools/Propulsion.Tool/Args.fs
- tools/Propulsion.Tool/Infrastructure.fs
- tools/Propulsion.Tool/Program.fs
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
- Implements inspecting or resetting checkpoints in Cosmos or Dynamo (for DynamoStoreSource, EventStoreDb.EventStoreSource, and Propulsion.Feed)
- Supports `dynamo` and `cosmos` stores
- Added support for `dynamo` to `project ... kafka` and project .. stats`
> Tool: Add checkpoint feature, project dynamo

- CHANGELOG.md
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- tools/Propulsion.Tool/Program.fs
Adds an --autoscale/-A switch to the propulsion tool to support autoscaling throughput of Cosmos containers and databases. Specifying this flag causes the --rus parameter to be interpreted as "Maximum RU/s" and changes the default value to 4000 RU/s (the minimum MaxRUs value allowed by Cosmos).
The hardcoding which existed in 'Equinox.CosmosStore.Core.Initialization.initAux' to enforce a default behavior of 'Manual throughput with 400 RU/s' has been brought into the propulsion tool.
> Propulsion.Tool: Add support for Cosmos Autoscaling

- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
At present, `FeedSourceBase` does not have logic to pick up new `trancheId`s that become available after a source starts.
The main scenario this affects is the generic `FeedSource` - the source needs restarting whenever a TrancheId is added.
This PR works around this shortcoming by defaulting to the well-known `DynamoStore.AppendsIndexId` when no events have yet been indexed, which covers all the cases for the current implementation.
resolves https://github.com/jet/propulsion/issues/146
> Hardwire reader for well-known DynamoStore AppendsEpochId

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
- tests/Propulsion.Kafka.Integration/Propulsion.Kafka.Integration.fsproj
- tools/Propulsion.Tool/Infrastructure.fs
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
Adds an optional Purge Interval to streams scheduler, which removes synced streams immediately after the state has been emitted
> Purge interval

- CHANGELOG.md
- src/Propulsion.DynamoStore.Lambda/Propulsion.DynamoStore.Lambda.fsproj
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.DynamoStore/Types.fs
- src/Propulsion/Propulsion.fsproj
Can't find any obvious way to remove the error (maybe a higher SDK ver will bring 6.0.5 so I don't need to add it explicitly?)
Would prefer not to add a 6.0.5 dep at top level like last commit does
> Remove FSharp.Core 6.0.4 bug workaround

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Projector.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
Improves the baseline impl of two key components in the Propulsion pipeline:
- Ingester: per Reader (Partition, Tranche etc) loop that manages:
- accepting data from a single partition's Reader
- managing the checkpointing as batches are confirmed complete
- Submitter: single loop that manages:
- ingesting items supplied by the Ingester instances
- propagating items into the Scheduler promptly and fairly
The key improvement is that the `Pump` methods now sleep until a trigger wakes them, rather than using a short sleep time and proactively checking whether some propagation activity has become possible. This provides the following benefits:
- there's no need to consider/tune the sleep interval
- under low load, there's dramatically less activity (CPU usage)
- under high load, there's never …
> Ingester/Submitter: Remove sleeps

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Projector.fs
- src/Propulsion/Streams.fs
Aligns Pump implementation techniques with those from #154
Key win is to replace the synchronous `GetConsumingEnumerable` with Channels, in order to shift the processing to the thread pool, saving a `Thread`
> Tune Dispatcher/Results processing

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Internal.fs
- src/Propulsion/Streams.fs
As per Ingester and Scheduler, replaces polling loop's `Thread.Sleep` with `Task.WhenAny`-based  awaiting of semaphores and/or Channels
- Adds logging of purged stream count
- Fixes erroneously removed laziness (`pending` vs `potential`)
- Adds logging of sleep time (resolves #83)
- Adds a `wakeForResults` option to provide optimal throughput
> Scheduler: Deterministic Sleeps

- README.md
- src/Propulsion.DynamoStore/AppendsIndex.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.DynamoStore/Types.fs
- tools/Propulsion.Tool/Program.fs
Adds a `propulsion index` command that inspects the index for a given table (without needing to look up stream names to use with `eqx`)
- Also adds an extension point to allow `DynamoStoreSource` user to override consumed tranches list
> DynamoStore: Add Index summary

- CHANGELOG.md
- src/Propulsion.DynamoStore.Lambda/Propulsion.DynamoStore.Lambda.fsproj
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.DynamoStore/Types.fs
- src/Propulsion/Propulsion.fsproj
- tests/Propulsion.Tests/ParallelThrottledValidation.fs
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
After much analysis...
- FSharp.Core `6.0.5` does not include the fix for https://github.com/dotnet/fsharp/issues/13165
- FSharp.Core `6.0.5-beta.22329.3` does
This PR downgrades to referencing 6.0.0, with the intention of requiring 6.0.x when it includes the fix
(Key reason to not even temporarily reference the beta is that 6.0.5 wins over the beta in semver, which would be very confusing)
> Downgrade FSharp.Core to 6.0.0

- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Streams.fs
Via profiling, internal signature changes toward `struct`/`task`
Calved from #167 as it's relatively noisy
> Bulk scheduling: struct/task optimizations

- src/Propulsion/Streams.fs
Key change is triggering wake via incoming batch when handler capacity available (as opposed to relying on the [formerly aggressive] timeout). While this is not critical for normal usage, it's extremely significant in conjunction with #165 as it makes scheduling instantaneous for relatively low load integration test scenarios
> Scheduler: Tuning

- src/Propulsion/Ingestion.fs
- src/Propulsion/Internal.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
Further optimizations based on both internal apps and https://github.com/jet/dotnet-templates/pull/121
- optimizations for scheduler hot paths with both low load and high load
- make prioritizing by stream payload size optional via `prioritizeLargePayloads`
> Scheduler tuning/profiling

- CHANGELOG.md
- README.md
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.MemoryStore/MemoryStoreLogger.fs
- src/Propulsion.MemoryStore/MemoryStoreSource.fs
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion.MemoryStore/ReactorInternal.fs
- src/Propulsion.MemoryStore/ReactorMonitor.fs
- src/Propulsion/Internal.fs
Enables awaiting async processing of Reactions within integration tests when used with Sources implemented with FeedBase (i.e. DynamoStore, EventStoreDb but not CosmosStore)
Note the wait is not completely deterministic in the manner that `Propulsion.MemoryStore`'s `AwaitCompletion` is.
Has been extensively tested with a significant [closed source] app and https://github.com/jet/dotnet-templates/pull/121. 
Polishes/extends the MemoryStore impl to align with the final naming
Resoves #64
> Add AwaitCompletion support for FeedSources

- CHANGELOG.md
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.CosmosStore/CosmosStoreParser.fs
- src/Propulsion.CosmosStore/CosmosStoreSource.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore/ReaderCheckpoint.fs
- src/Propulsion.CosmosStore3/Propulsion.CosmosStore3.fsproj
- src/Propulsion.DynamoStore/AppendsEpoch.fs
- src/Propulsion.DynamoStore/AppendsIndex.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.DynamoStore/Types.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.MemoryStore/MemoryStoreSource.fs
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/Streams.fs
- tools/Propulsion.Tool/Program.fs
Needed for https://github.com/oskardudycz/EventSourcing.NetCore/pull/84 and https://github.com/jet/dotnet-templates/pull/121 to handle ESDB
- Adds `Propulsion.Feed.ReaderCheckpoint.MemoryStore.create`
> Esdb+Sss Sources: Add fromTail, categoryFilter

- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore/ReaderCheckpoint.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/PeriodicSource.fs
- src/Propulsion.Kafka/Codec.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.MemoryStore/MemoryStoreSource.fs
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion/Streams.fs
Cleanup re https://github.com/jet/dotnet-templates/pull/122
Includes Straggler Kafka changes
> Equinox v4 Updates

- CHANGELOG.md
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.MemoryStore/MemoryStoreSource.fs
- src/Propulsion/Pipeline.fs
- tests/Propulsion.Tests/SourceTests.fs
- tests/Propulsion.Tests/TestOutputLogger.fs
See tests - executes a single pass (parallel) ingestion of all tranches of a Source until they've all been Handled by a Sink.
> Feed: Add SinglePassFeedSource

- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion/Streams.fs
Fixes an issue introduced in the original implementation of purging in #97 
Issue was that processing can stop (Scheduler reports Holding 0 batches and no active work) when
- compaction takes effect (Ingester has sufficient read ahead margin to trigger compaction)
- purge removes a stream from the buffer at the point where work has been completed that has yet to enter the pending batches list
This fix causes stream requirements in a batch to immediately be declared complete on ingestion where the underlying stream queue entry has been removed; previously this prevented the batch from being declared complete
> Streams: Fix handling of purge under compaction

- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion.MemoryStore/MemoryStoreSource.fs
- src/Propulsion.MessageDb/MessageDbSource.fs
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
- src/Propulsion/Internal.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Pipeline.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
- tests/Propulsion.Tests/ProgressTests.fs
- tests/Propulsion.Tests/SourceTests.fs
- DynamoStore already correctly implements the ITimelineEvent.Size
- Skipping CosmosStore for now
> Scheduler: Fix state logging, extend stats

- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion.MessageDb/MessageDbSource.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Internal.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Pipeline.fs
- src/Propulsion/Streams.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
- tests/Propulsion.Tests/SourceTests.fs
- tools/Propulsion.Tool/Program.fs
> Scheduler: Simplification & fixes

- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.DynamoStore.Indexer/Propulsion.DynamoStore.Indexer.fsproj
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.DynamoStore/Types.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- tests/Propulsion.Tests/ParallelThrottledValidation.fs
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
The fix for https://github.com/dotnet/fsharp/issues/13165 is included in FSharp.Core 6.0.6
(Compile error suggests https://github.com/dotnet/fsharp/issues/12706 is still at large though)
> Target Equinox 4.0.0-rc6 + FSharp.Core 6.0.7

- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Streams.fs
MaxIngest was previously a far more significant parameter for tuning performance under high throughput. This adjustment is intended to convey that this is of less consequence, due to:
- Because the Submitter continually submits events as they arrive from the Ingesters, there is no longer a merging cost per batch that needs to be minimised to the same degree as previously
- The Scheduler Engine was simplified to ingest a single batch at a time (which it then immediately dispatches any work that results from)
- The Submitter now has a deterministic wait for input capacity (previously it was on a 1-5ms timer so buffering was critical to avoid the scheduler falling idle while there are batches in the Submitter)
The bottom line is that this parameter should only ever need tweaking under …
> Streams: Rename maxIngest  -> pendingBufferSize

- README.md
- src/Propulsion.DynamoStore.Indexer/Handler.fs
- src/Propulsion.DynamoStore.Lambda/SqsNotificationBatch.fs
- src/Propulsion.DynamoStore.Notifier/Handler.fs
- src/Propulsion.DynamoStore/AppendsEpoch.fs
- src/Propulsion.DynamoStore/AppendsIndex.fs
- src/Propulsion.DynamoStore/DynamoStoreIndex.fs
- src/Propulsion.DynamoStore/DynamoStoreIndexer.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.DynamoStore/Types.fs
- tests/Propulsion.Tests/AppendsIndexTests.fs
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
- tools/Propulsion.Tool/Args.fs
- tools/Propulsion.Tool/Program.fs
Arising from discussions around #200, this replaces the term 'tranche' in the DynamoStore Index with the more common term 'partition'
resolves #201
> DynamoStore Index: rename tranche->partition

- src/Propulsion.CosmosStore/CosmosStoreParser.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion.MemoryStore/MemoryStoreSource.fs
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
- src/Propulsion/Streams.fs
Stragglers from #204 re MemoryStore, SqlStreamStore, EventStoreDb, Cosmos
Overloads for Async handlers for `Streams.Default.Config.Start` and `Propulsion.Kafka.StreamsProducerSink.Start`
> Sources: Add missing category filter support

- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.MessageDb/MessageDbSource.fs
- tests/Propulsion.MessageDb.Integration/Tests.fs
This meant that the read logic was re-reading the final event of the preceding batch
(In the case of the tail batch, that resulted in a single item batch being loaded and parsed each time, with incorrect statistics and tail sleeps as `isTail` will perpetually be `false`)
> fix: MessageDB is off-by-one when reading the category messages

- Directory.Build.props
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.MessageDb/MessageDbSource.fs
- src/Propulsion/Internal.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Submission.fs
- tests/Propulsion.Tests/SourceTests.fs
- We had a stray `Async.StartAsChild` inside a `task` computation expression
- We were passing a `ValueTask<bool>` where what we wanted was a `Task`
> cleanup some task usage

- src/Propulsion/Ingestion.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
I noticed that a lot of the objects that were surviving in my memory leak repro were CancellationTokenSources
Adding a use seems to solve for our memory leak
See this related stack overflow https://stackoverflow.com/questions/6960520/when-to-dispose-cancellationtokensource
> fix: Add a 'use' around linked cancellation tokens

- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.DynamoStore.Indexer/Handler.fs
- src/Propulsion.DynamoStore.Notifier/Handler.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
As of https://github.com/jet/equinox/pull/401
- non-Tip batches no longer bear an `"a"` field (as all writes must feed through Tip to guarantee correct arrival order for Indexer etc)
- Indexer needs to be using same in order for it in turn to be able to guarantee same for the Notifier
Technically, the existing code would continue to work, but an out of date version would mean the Notifier cannot be trusted where the Index writes are not guaranteed to have been fed through tip.
Hence this intentional breaking change is to force people to upgrade Indexers to latest to match the Equinox behavior.
> DynamoStore: Handle removal of "a" fields from calves

- src/Propulsion.CosmosStore/ReaderCheckpoint.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.MessageDb/ReaderCheckpoint.fs
- src/Propulsion.SqlStreamStore/ReaderCheckpoint.fs
- src/Propulsion/Feed.fs
- tests/Propulsion.MessageDb.Integration/Tests.fs
- tools/Propulsion.Tool/Args.fs
- tools/Propulsion.Tool/Program.fs
It's a feature specific to Cosmos/Dynamo stores. Having Sql checkpointers implement the same interface causes some confusion
e.g. We will log that there's a "checkpoint event interval" even if our checkpoints aren't event based at all.
I misunderstood the concept myself and thought it was there to tell propulsion to "only commit a checkpoint at most once every interval"
> remove frequency from checkpointer.Start interface

- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore/ReaderCheckpoint.fs
- src/Propulsion.CosmosStore3/Propulsion.CosmosStore3.fsproj
- src/Propulsion.DynamoStore/AppendsEpoch.fs
- src/Propulsion.DynamoStore/AppendsIndex.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.DynamoStore/Types.fs
- src/Propulsion.EventStore/Checkpoint.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion/Propulsion.fsproj
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
Deal with transition from `list` to arrays, and category name moving from resolve to Category...
> Target Equinox 4.0.0-rc.12.8

- CHANGELOG.md
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.CosmosStore/CosmosStoreSource.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore/ReaderCheckpoint.fs
- src/Propulsion.DynamoStore.Notifier/Handler.fs
- src/Propulsion.DynamoStore/AppendsEpoch.fs
- src/Propulsion.DynamoStore/AppendsIndex.fs
- src/Propulsion.DynamoStore/DynamoStoreIndex.fs
- src/Propulsion.DynamoStore/DynamoStoreIndexer.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.DynamoStore/Store.fs
- src/Propulsion.DynamoStore/Types.fs
- src/Propulsion.EventStore/Checkpoint.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.MemoryStore/MemoryStoreSource.fs
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion/Pipeline.fs
- src/Propulsion/Streams.fs
- tools/Propulsion.Tool/Infrastructure.fs
- tools/Propulsion.Tool/Program.fs
Polished Cosmos/EventStoreSink and Pruners 
- better error management under rate limiting (some message parsing was Cosmos V2 SDK specific)
- Exposed Stats types to match other sinks
- [Pushed cosmos exn parsing into `Equinox.CosmosStore.Exceptions`](https://github.com/jet/equinox/pull/416)
- Targeted interim `Equinox` v `4.0.0-rc.12.12` release
- Made CosmosStoreSink maxBytes more conservative (was 1MB, now 256KB) as erroring with `RequestEntityTooLarge` (wgy and/or the exact real limit not fully root caused)
> fix(CosmoStoreSink): Improve error handling

- CHANGELOG.md
- src/Propulsion.CosmosStore/CosmosStorePruner.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.CosmosStore/EquinoxSystemTextJsonParser.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Internal.fs
- src/Propulsion/Sinks.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Sync.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
Add
- `Stats`: `DumpState` to include custom output alongside internal ones
- Generalize stats gathering to `LatencyStatsSet`
- Add `index` and `eventType` properties to Unhandled exception logging
- Emits stuck/failing stream names in head batch State output after `failTheshold` (defaults to StateInterval)
- Reordered output so it gets emitted after the normal Stats on shutdown
- Ingester emits state on shutdown
Change
- Sinks.StartBatched results now require a latency per result (as a `TimeSpan`)
- Major cleanup of internal timing/progress management
> feat(Streams)!: Stats/error logging polish

- src/Propulsion.CosmosStore/CosmosStoreSource.fs
- src/Propulsion.CosmosStore/FeedObserver.fs
- src/Propulsion.DynamoStore.Lambda/SqsNotificationBatch.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Feed/PeriodicSource.fs
- src/Propulsion.MessageDb/MessageDbSource.fs
- src/Propulsion/Feed.fs
- src/Propulsion/FeedMonitor.fs
- src/Propulsion/Pipeline.fs
- tests/Propulsion.MessageDb.Integration/Tests.fs
- tests/Propulsion.Tests/SourceTests.fs
- tools/Propulsion.Tool/Program.fs
Fixes an oversight: `Flush` needed to yield the positions for the Lambda template in `dotnet-templates` to work cleanly (and that return value had erroneously been dropped in adding CosmosStore's FeedMonitor support recently)
> fix(DynamoStore)!: Restore TranchePositions to Flush

- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore3/Propulsion.CosmosStore3.fsproj
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion/Propulsion.fsproj
- tests/Propulsion.Kafka.Integration/Propulsion.Kafka.Integration.fsproj
- tests/Propulsion.MessageDb.Integration/Propulsion.MessageDb.Integration.fsproj
The FsCodec update in question ups the minimum Newtonsoft.Json version to 13.0.3
This trims overrides that were in place to ensure the correct version of the transitive dependency was being used
The Equinox update is solely for completeness
> chore: Update to FsCodec.NewtonsoftJson 3.0.0-rc.14.1

- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/FeedObserver.fs
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion/Pipeline.fs
- tools/Propulsion.Tool/Program.fs
Polishing the `AwaitWithStopOnCancellation` behavior for Feed and Cosmos sources
- Remove erroneous Cosmos logging
- Resolve Ingester wait deadlock
- Handle cancellation via Ctrl-C correctly
> fix: Correct/polish shutdown behaviors

- src/Propulsion/Sinks.fs
- src/Propulsion/Streams.fs
- tools/Propulsion.Tool/Sync.fs
the `requireComplete` flag (normally used with SinglePassFeedSource; not a mainline scenario) currently has the following semantics:
- alert/don't dispatch if there's a gap
- BUT trust the first batch received to
a. be safe to dispatch
b. dictate the write position going forward
When doing a full projection against a changefeed with mutated items (manually updated outside Equinox), this can lead to out of order events
The change here is to make the relatively loose `requireComplete` semantic into a more useful one, `requireAll`, which requires all events processed to start from `0` for each and every stream.
Its conceivable that another more tolerant mode is possible, but this change to the semantics covers both scenarios:
1. projecting from a broken Event Store with events arriving out …
> fix(Scheduler)!: requireComplete -> requireAll

- CHANGELOG.md
- src/Propulsion/Internal.fs
- src/Propulsion/Streams.fs
- tools/Propulsion.Tool/Infrastructure.fs
- tools/Propulsion.Tool/Sync.fs
For some workloads it's really useful to break down latencies by stream category
And an experimental feature: you can also add user activities via `stats.Latency.Record(label: string, TimeSpan)`
> feat(Scheduler): Success latencies by category

- CHANGELOG.md
- src/Propulsion.CosmosStore/EquinoxSystemTextJsonParser.fs
- tools/Propulsion.Tool/Args.fs
Propulsion sync fails to populate the `correlationId`/`causationId` fields in the `ITimelineEvent`.
While this is rarely important (correlation/causation identifiers and event metadata should rarely be touched by application logic), it's critical to `propulsion sync` faithfully copying that field; particularly when copying from Cosmos to Cosmos
> fix(CosmosStore): Propagate correlationId, causationId
