- CHANGELOG.md
- src/Propulsion.Kafka/Bindings.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion.Kafka0/Bindings.fs
- tests/Propulsion.Kafka.Integration/ParallelIntegration.fs
I definitely wrote this code at some point... it's kinda useful :(
> Add 0.x error check on produce

- CHANGELOG.md
- Propulsion.sln
- README.md
- build.proj
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- tools/Propulsion.Tool/Infrastructure/Infrastructure.fs
- tools/Propulsion.Tool/Program.fs
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
Addressing #6, this adds a `Propulsion.Tool`, extracted from `Equinox.Tool`
> Add Propulsion.Tool

- Directory.Build.props
- azure-pipelines.yml
- build.proj
- tests/Propulsion.Kafka.Integration/Propulsion.Kafka.Integration.fsproj
- tests/Propulsion.Kafka0.Integration/Propulsion.Kafka0.Integration.fsproj
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
Adding timeouts etc as green builds are becoming rare in #12
> Tidy build scripting

- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.Kafka0/Propulsion.Kafka0.fsproj
- src/Propulsion/Propulsion.fsproj
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
Thanks for testing the alpha! 🙂
> update MinVer from 2.0.0-alpha.2 to 2.0.0-rc.1

- CHANGELOG.md
- src/Propulsion.EventStore/Checkpoint.fs
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.EventStore/EventStoreSource.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion/Streams.fs
Fixes a NRE reported by @jgardella
Includes related tidyups
> Fix to handle null Kafka Message keys in Propulsion.Kafka

- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.Kafka0/Propulsion.Kafka0.fsproj
- src/Propulsion/Propulsion.fsproj
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
> update MinVer to 2.0.0

- src/Propulsion.EventStore/EventStoreSource.fs
As noted in https://github.com/jet/propulsion/pull/1#discussion_r372666647 renaming this small typo
> rename cosmosIngester to ingester for ES

- .editorconfig
- src/Propulsion.EventStore/Checkpoint.fs
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/EventStoreSource.fs
- src/Propulsion.EventStore/Infrastructure.fs
- src/Propulsion.EventStore/StripedIngester.fs
- src/Propulsion/Infrastructure.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Projector.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
Similar to https://github.com/jet/FsCodec/pull/32 and https://github.com/jet/equinox/pull/191, a bunch of small style changes to make it more consistent
> minor style changes

- DOCUMENTATION.md
- README.md
- diagrams/IngestersContainer.puml
- diagrams/PublishersContainer.puml
- diagrams/ReactorsContainer.puml
- diagrams/context.puml
:point_right: https://github.com/jet/propulsion/blob/diag/DOCUMENTATION.md#overview
> Diagrams & docs

- CHANGELOG.md
- src/Propulsion.Kafka/Binding.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka0/Binding.fs
Prompted by discussions with @fnipo
> Kafka: ConsumeResultContext wiring

- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
> Reintroduce parallelism in test suite

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
Adds a Sink that trims events fed into the sink from a given Store
> Cosmos: Add CosmosPruner

- CHANGELOG.md
- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion/Streams.fs
Detail tweaks to enhance output for `proArchiver` template
> Cosmos: Log tweaks for CosmosSink

- CHANGELOG.md
- src/Propulsion.Cosmos/CosmosPruner.fs
Off by one error due to Equinox API change (which on reflection I should not have made :()
> Fix CosmosPruner offset computation

- README.md
@absolutejam asked this on the DDD-CQRS-ES forum; harvesting as a FAQ
> Add testing FAQ from @absolutejam

- README.md
Backfilling docs thanks to a question from @absolutejam
Much thanks to @ylorph for feedback on earlier iterations of it on the DDD-CQRS-ES slack
> Add FAQ re ESDB subscriptions comparison

- CHANGELOG.md
- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- tools/Propulsion.Tool/Program.fs
Tidying wart introduced in `2.10.0-rc1`
> Cosmos: Fix createObserver signature wart

- CHANGELOG.md
- src/Propulsion/Streams.fs
Tweaks for stream version management within handlers
> Add SpanResult.NoneProcessed, StreamSpan.Version

- CHANGELOG.md
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Streams.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
Review shows they are now equivalent; Will Remove in a separate PR
> Tidy+Deprecate StreamsConsumerStats

- src/Propulsion.Cosmos/EquinoxCosmosParser.fs
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- tools/Propulsion.Tool/Program.fs
See Manual Checkpoint signature change per https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2488
> CosmosStore: Target SDK 3.20.0-preview

- CHANGELOG.md
- Directory.Build.props
- Propulsion.sln.DotSettings
- README.md
- azure-pipelines.yml
- src/Propulsion.Cosmos/CosmosSink.fs
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.EventStore/EventStoreSink.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion/Infrastructure.fs
- src/Propulsion/Projector.fs
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/Streams.fs
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
Also includes removal of warnings etc but zero functional changes
> Remove net461-specific package variants

- CHANGELOG.md
- src/Propulsion.Kafka/Codec.fs
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion/PropulsionPrometheus.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
notably to use the changed `Serdes` contract
> Kafka: Update to FsCodec 2.3.0

- CHANGELOG.md
- src/Propulsion/Parallel.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
- tests/Propulsion.Kafka.Integration/Propulsion.Kafka.Integration.fsproj
- tools/Propulsion.Tool/Infrastructure.fs
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
The main handling being leant on was that for Tuples
Replacing with struct tuples makes it work without and reduces allocations
> Remove Destructurama dep

- CHANGELOG.md
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Projector.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
- Use channels where relevant
- Apply Tasks for all Supervision trees
> Scheduler Tasks/Channels

- CHANGELOG.md
- src/Propulsion/Streams.fs
> Scheduler memory usage

- CHANGELOG.md
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion/Streams.fs
Follow-up aligning more trees with #156
> Feed: Use Tasks for supervision trees

- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
- src/Propulsion/Internal.fs
- src/Propulsion/Streams.fs
Validated in https://github.com/jet/dotnet-templates/pull/121
:thanks: @ylorph and @thefringninja for the assistance in getting it all working
> Esdb: Fix derivation of tail position

- .editorconfig
- src/Propulsion.Cosmos/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion.CosmosStore/CosmosStoreSource.fs
- src/Propulsion.DynamoStore.Lambda/SqsNotificationBatch.fs
- src/Propulsion.DynamoStore.Notifier/Handler.fs
- src/Propulsion.DynamoStore/DynamoStoreIndexer.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Submission.fs
- tests/Propulsion.Tests/SourceTests.fs
> FeedSource polish

- Propulsion.sln
- src/Propulsion.Cosmos/Propulsion.Cosmos.fsproj
- src/Propulsion.CosmosStore/CosmosStoreParser.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore/ReaderCheckpoint.fs
- src/Propulsion.CosmosStore3/Propulsion.CosmosStore3.fsproj
- src/Propulsion.DynamoStore/AppendsEpoch.fs
- src/Propulsion.DynamoStore/AppendsIndex.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStore/EventStoreReader.fs
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.MemoryStore/MemoryStoreLogger.fs
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/Streams.fs
- tools/Propulsion.Tool/Program.fs
> Target Equinox 4.0.0-rc.3

- src/Propulsion.MessageDb/Propulsion.MessageDb.fsproj
Npgsql has released v7, so let's get up to date in MessageDB
> Upgrade Npgsql to v7 now that it's GA

- src/Propulsion.DynamoStore.Indexer/Handler.fs
The Propulsion Indexer presently notes changes to any stream, except for the two index categories - `AppendsIndex` and `AppendsEpoch`
This extends the filtering to also omit streams prefixed with `'$'`. At the present time, this only affects `ReaderCheckpoint` streams, but it can obviously be leveraged more generally.
resolves: #197
> DynamoStore: Don't index '$'-prefixed streams

- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore/ReaderCheckpoint.fs
- src/Propulsion.DynamoStore/AppendsEpoch.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
Deal with minor breaking changes (removal of struct tuples)
> Target Equinox 4.0.0-rc.8

- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
- tools/Propulsion.Tool/Args.fs
- tools/Propulsion.Tool/Program.fs
As suggested by @nordfjord, adding overloads to align with common practice of whitelisting categories
> DynamoStore: LoadMode category lists, withData naming

- src/Propulsion.MessageDb/Propulsion.MessageDb.fsproj
- tests/Propulsion.MessageDb.Integration/Tests.fs
As discussed. This PR contains some improvements to make the messagedb tests clearer
> Improve the mdb tests

- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/ProducerSinks.fs
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/Sinks.fs
- src/Propulsion/Sync.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
via https://github.com/jet/dotnet-templates/pull/130, stragglers for #208
> Sync, Kafka: Straggler FSharpAsync overloads

- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore3/Propulsion.CosmosStore3.fsproj
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.Feed/FeedReader.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.Feed/PeriodicSource.fs
- src/Propulsion.Kafka/Codec.fs
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.MemoryStore/MemoryStoreLogger.fs
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion.MessageDb/MessageDbSource.fs
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/Sinks.fs
- src/Propulsion/Streams.fs
- src/Propulsion/Sync.fs
- tests/Propulsion.Kafka.Integration/ConsumersIntegration.fs
- tests/Propulsion.MessageDb.Integration/Propulsion.MessageDb.Integration.fsproj
- tests/Propulsion.Tests/SourceTests.fs
- tools/Propulsion.Tool/Program.fs
- Fix MemoryStoreLogger signature
- Add FSharpAsync overloads for FeedSource
> FSharpAsync stragglers + FsCodec 3rc9.6

- src/Propulsion.CosmosStore/ChangeFeedProcessor.fs
- src/Propulsion/Sinks.fs
- tools/Propulsion.Tool/Args.fs
Removes need to log ChangeFeed Items limit independently in external wiring
> refactor: Log tweaks

- src/Propulsion/Internal.fs
- src/Propulsion/Streams.fs
Under load, as cancellations of the waits kick in, this bug results in the Dispatcher getting handed capacity beyond the specified max degree of parallelism, which means it will dispatch too many concurrent threads
cc @epNickColeman
> fix: Remove over-Release on cancellation in WaitButRelease 

- src/Propulsion.DynamoStore.Constructs/DynamoStoreIndexerLambda.fs
- src/Propulsion.DynamoStore/DynamoStoreSource.fs
- src/Propulsion.EventStoreDb/EventStoreSource.fs
- src/Propulsion.Feed/FeedSource.fs
- src/Propulsion.SqlStreamStore/SqlStreamStoreSource.fs
Based on conversation here https://github.com/equinox-project/equinox-js/pull/32#discussion_r1328010227
> feat(*Source)!: replace categoryFilter with streamFilter

- tools/Propulsion.Tool/Args.fs
- tools/Propulsion.Tool/Infrastructure.fs
- tools/Propulsion.Tool/Program.fs
Finally removing `MissingArg`!
> refactor(Tool): Arg parsing cleanup

- CHANGELOG.md
- tools/Propulsion.Tool/Args.fs
- tools/Propulsion.Tool/CosmosDumpSource.fs
- tools/Propulsion.Tool/Program.fs
- tools/Propulsion.Tool/Project.fs
- tools/Propulsion.Tool/Propulsion.Tool.fsproj
Enables exporting with `eqx query` and then using `propulsion project stats json FILENAME` to walk the data
> feat(Tool): Add JSON file support

- tools/Propulsion.Tool/Project.fs
Adds event/category filtering support for `propulsion project`
> feat(Tool): Add filtering, stats

- src/Propulsion/Internal.fs
- tools/Propulsion.Tool/Sync.fs
Stragglers re #252
- Fix subcommand name (docs already said `sync` in https://github.com/jet/equinox/pull/445 etc, but code was still doing `project)
- Move helper data structures used in `propulsion-indexer` template into `Propulsion.Internal`:
- `CategoryCounters`
- `EventTypeLatencies`
> feat(Internal)!: Expose Stats helpers re #252

- .github/workflows/ci.yaml
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore3/Propulsion.CosmosStore3.fsproj
- src/Propulsion.DynamoStore.Constructs/Propulsion.DynamoStore.Constructs.fsproj
- src/Propulsion.DynamoStore.Indexer/Propulsion.DynamoStore.Indexer.fsproj
- src/Propulsion.DynamoStore.Lambda/Propulsion.DynamoStore.Lambda.fsproj
- src/Propulsion.DynamoStore.Notifier/Propulsion.DynamoStore.Notifier.fsproj
- src/Propulsion.DynamoStore/Propulsion.DynamoStore.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.EventStoreDb/Propulsion.EventStoreDb.fsproj
- src/Propulsion.Feed/Propulsion.Feed.fsproj
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- src/Propulsion.MessageDb/Propulsion.MessageDb.fsproj
- src/Propulsion.SqlStreamStore/Propulsion.SqlStreamStore.fsproj
- src/Propulsion/Propulsion.fsproj
Versioning and package vaidation as per Equinox - `3.0.0-rc.12` will be a stable base
Don't have any specific plan as to when to mark 3.0.0 final at the present time
> chore: Add Package Validation

- src/Propulsion.CosmosStore/CosmosStoreSink.fs
- src/Propulsion.CosmosStore/Propulsion.CosmosStore.fsproj
- src/Propulsion.CosmosStore3/Propulsion.CosmosStore3.fsproj
- src/Propulsion.DynamoStore.Notifier/Propulsion.DynamoStore.Notifier.fsproj
- src/Propulsion.EventStore/Propulsion.EventStore.fsproj
- src/Propulsion.Feed/Propulsion.Feed.fsproj
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion.MemoryStore/Propulsion.MemoryStore.fsproj
- tools/Propulsion.Tool/Sync.fs
Exposes the sink validation option as a tool argument
> feat(propulsion sync): Add --requireAll
